project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "笑面狐"
  site-url: https://laq12345.github.io
  favicon: misc/info/favicon.jpg
  repo-url: https://github.com/laq12345/laq12345.github.io
  repo-actions: [edit, issue]
  
  page-footer: 
    left: "&copy; Copyright 2025, Liu Aoqi"
    right: 
      - icon: github
        href: https://github.com/laq12345/laq12345.github.io

  navbar: 
    background: "#A9CCE3"
    search: true
    left: 
      - text: "资料"
        href: projects/projects.qmd
      
      - text: "科研"
        href: research/research.qmd
        
      - text: "代码"
        href: code/code.qmd
           
      - text: "ICU"
        href: icu/icu.qmd

      - text: "笔记"
        href: blog/blog.qmd
        
      - text: "关于"
        href: about_me.qmd
        
      #- text: "CV"
      #  href: misc/info/CV-CZ-2407.pdf


    right: 
      - icon: journal-richtext
        href: misc/info/resume.pdf
        target: _blank 
      - icon: github
        href: https://github.com/laq12345
        target: _blank
#      - text: "{{< fa brands bluesky >}}"
#        href: https://bsky.app/profile/hegang.bsky.social
#        target: _blank
#      - icon: twitter-x 
#        href: https://twitter.com/DrGangHe
#        target: _blank        
      - icon: mailbox2-flag
        href: mailto:2713874272@qq.com


format:
  html:
    theme: styles.scss
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center



