project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "笑面狐"
  site-url: https://laq12345.github.io
  favicon: misc/info/favicon.jpg
  repo-url: https://github.com/laq12345/laq12345.github.io
  repo-actions: [edit, issue]
  
  page-footer: 
    left: "&copy; Copyright 2025, Liu Aoqi"
    right: 
      - icon: github
        href: https://github.com/laq12345/laq12345.github.io

  navbar: 
    background: "#A9CCE3"
    search: true
    right: 
      - text: "Projects"
        href: projects/projects.qmd
      
      - text: "科研"
        href: research/research.qmd
        
      - text: "R packages"
        href: rpkg/rpkg.qmd
           
      - text: "ICU"
        href: icu/icu.qmd

      - text: "笔记"
        href: blog/blog.qmd
        
      - text: "About me"
        href: about_me.qmd
        
      #- text: "CV"
      #  href: misc/info/CV-CZ-2407.pdf


format:
  html:
    theme: styles.scss


