---
title: "5min中文自我介绍（PPT）"
author: "刘奥奇"
description: |
  中文自我介绍，包括基本信息、学业和英语成绩、荣誉、科研、实践、技能和研修计划
date: "2025-08-31"
categories: [interview, introduction]
title-block-banner: false
format: 
  html:
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: false
---

### 5min中文PPT

<a href="https://github.com/laq12345/laq12345.github.io/tree/main/resource/introduction.pptx" download="自我介绍.pptx" class="btn btn-outline-primary">下载PPT </a>

各位老师好，我是郑州大学临床医学专业的学生刘奥奇。能参加这次预推免并向各位老师介绍自己，我倍感荣幸。

接下来我将从以下几个方面进行介绍。

首先是基本信息。我是汉族，于2002年10月1日出生河南省周口市，目前就读于郑州大学临床医学专业。

学业成绩是我本科阶段的突出亮点。本科前8个学期，我的平均绩点为3.8（满绩4.0），在专业572人中排名第11，占比约1.92%。其中40门核心课程成绩在90分以上，15门在95分以上，像病理生理学、药理学及内科学等均取得了高分。

英语方面，我的四级总分565分，六级总分520分。

自入学以来我连续两年获评郑州大学三好学生称号，国家励志奖学金、郑州大学一等奖学金等。

科研竞赛方面。我参与过大学生创新创业训练计划项目、北京脑举行的暑期培训营、挑战杯、中国国际大学生创新大赛以及大学生医学创新大赛等多个项目。

大二时，我加入了一项大创项目，主要研究小鼠中哮喘的调控机制，在此期间我熟练掌握了PCR、Western Blot等实验技术。

由于对科学研究很感兴趣，我报名参加了北京脑神经与认知科学暑期培训班，聆听了许多大佬的讲座，了解到了很多前沿的科学知识，并且我们小组最终在文献汇报比赛中拿到了一等奖。

之后，我借助公共数据库，研究了AARS1作为乳酰基转移酶在肿瘤的临床相关性、肿瘤特征及乳酸代谢中的作用，发现AARS1在肿瘤中广泛高表达，且与乳酸代谢增强密切相关，影响患者生存。最后我们通过Western Blot和qPCR对结果进行了验证。

我还参与了一项“中国国际大学生创新大赛”项目，我们项目名称为“智绘·好孕”，是一款植入前胚胎植入潜能检测试剂盒。我的主要工作是负责项目的单细胞数据分析流程的构建，包括整合RNA-seq、ATAC-seq和CNV数据，同时利用获取的特征基因构建随机森林模型，用于预测胚胎细胞的植入潜能。目前，相关内容已授权了两项软著，我也在此过程中掌握了单细胞数据分析的基本流程。

我参加了全国大学生医学创新大赛，并获全国总决赛银奖。

实践方面，实习期间我跟随临床老师学到了不少知识，还在郑大一附院老师的带领下参观了ICU病房，这让我对重症医学领域产生了浓厚兴趣。

技能上，我已经熟练地掌握了使用R语言和Python数据分析，我从老师那里借了服务器账号练习Linux技能，现已足够熟悉Linux服务器的基本操作方法。

另外，我还比较熟练地掌握了CPR、换药术和四大穿刺等临床技能。未来我会继续努力，将这些技能熟练应用到临床和科研工作中。

关于未来，我希望能在华西医院深造，并且制定了详细的计划。入学前，学习上要继续巩固临床知识、提升专业英语水平、研读文献、学习重症医学教材及生信和实验知识；技能上要熟练掌握各类临床技能，精进编程能力；生活上要保持健康习惯，坚持锻炼，阅读课外书等。

我目前比较感兴趣的研究方向为脓毒症与感染性休克的调节机制及治疗策略。计划在大五期间，每周阅读3篇高质量文献，用Zotero建立文献管理库，总结高分文章的研究思路与方法，确定研究方向，再从公共数据库下载合适的数据集进行分析，然后整理、优化并验证结果，最后得出结论并撰写论文。

入学后的计划也已制定：研一要取得优异的学业成绩，争取奖学金，继续备考六级，争取考到600分以上；积极阅读文献、参与科研并发表论文；努力学习临床知识，掌握临床技能。研二继续学习专业知识，磨练临床技能，考取执业医师证书，同时尝试发表更具创新性的论文。研三要在ICU学习中向各位老师请教，掌握临床技能并考取相关证书，同时准备申博材料，争取读博机会。若能顺利读博，希望能独立开展课题，发表更高水平的论文。最终，我希望能在三甲医院的重症医学科就业，若有机会，非常渴望能留在华西医院工作。

以上就是我的个人介绍，感谢老师们的聆听！