---
title: "5min英文自我介绍（PPT）"
author: "刘奥奇"
description: |
  英文自我介绍，包括基本信息、学业和英语成绩、荣誉、科研、实践、技能和研修计划
date: "2025-08-31"
categories: [interview, introduction]
title-block-banner: false
format: 
  html:
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: false
---

### 5min英文PPT

<a href="https://github.com/laq12345/laq12345.github.io/tree/main/resource/" download="自我介绍.pptx" class="btn btn-outline-primary">下载PPT </a>

Good morning, professors.

My name is **Liu Aoqi**, and I am currently studying Clinical Medicine at Zhengzhou University. It is a great honor to be here.

I’d like to share my story in these parts.

**Part one, some basic information.**\
I’m Han Chinese, born on **October 1, 2002**, in **Zhoukou, Henan Province.**

**Part two, my academic performance.**\
I have consistently achieved high academic results with an average GPA of **3.8** out of **4.0**, ranking **11th** out of 572 **students** in my major, which places me in the top **2%**. I’ve excelled in **40** core courses such as Pathophysiology /ˈpæθəʊfɪzɪˈɒlədʒi/, Pharmacology /ˌfɑːməˈkɒlədʒi/, and Internal Medicine and scored **565 on the CET-4** and **520 on the CET-6**.

In addition, I have received several awards, including **the National Inspirational Scholarship**, **first-class scholarship** and the "**merit student**" title.

**Part three, my research and competition experience.**\
I’ve been involved in several projects. One of my projects was about investigating asthma regulation in mice and I learned experimental techniques such as **PCR** and **Western Blot**.

I was especially excited to join a summer training class, where I listened to lectures from top scientists, and our group won the **first prize** in a literature presentation competition.

We know lactate plays a critical role in cancers, and a new modification called **protein lactylation** is important — but the enzyme */ˈenzaɪm/* wasn’t clear. Recently, some studies suggested **AARS1** might be that enzyme. So, I analyzed data to see how AARS1 is related to clinical relevance, hallmarks and lactate metabolism. I found that **AARS1 is highly expressed in many cancers**, linked to higher lactate levels, and affects the survival of patients. Finally, We also used **qPCR** and **Western Blot** to confirm our findings.

I also worked on a project called **“ZhiHui·HaoYun”** — a test kit to predict embryo implantation potential. My main job was to build the **single-cell data analysis pipeline**. I combined data from **RNA-seq**, **ATAC-seq**, and **CNV**, and used the results to train a **random forest model** to predict embryo quality, which has currently been granted two software copyrights, and I’ve learned the basic workflow of single-cell data analysis.

I also participated in a competition and won the silver award in the national finals.

**Part four, my practical experiences.**\
During my clinical internship, I also visited the **ICU at the First Affiliated */əˈfɪlieɪtɪd/* Hospital of Zhengzhou University**, which really sparked my interest in critical care medicine.

I’m good at using **R** for data cleaning, analysis, and visualization. And I am also familiar with Python for data analysis and the basic operations of Linux servers.\
Clinically, I’ve mastered **CPR** and **wound dressing**. I’ll keep improving these skills for both clinical work and research.

**Finally, my future goals.**\
Before starting graduate school, I plan to:

-   Review clinical knowledge, improve medical English, and read more papers,

-   Learn more about **bioinformatics**, experimental techniques, and improve programming abilities

-   keep a healthy lifestyle

I’m particularly interested in studying the mechanisms and therapies for sepsis and septic shock. In my fifth year, I plan to read **3 papers per week** and learn from their methods. Then download and analyze the data. Finally, verify the results and publish the paper.

Here’s my study plan after enrollment:

-   **Year 1**: Get good grades, improve my CET-6 (target: 600+), read papers and start research.

-   **Year 2**: prepare for the **Medical Licensing Exam**, and publish innovative papers.

-   **Year 3**: prepare for PhD applications.\
    If I get the chance to do a PhD, I hope to lead my own project and publish high-impact papers.

In the long run, I want to work in the **ICU of a three-A hospital**. And if possible, I hope to work at West China Hospital.

That’s all for my introduction.