---
title: "Machine learning for the prediction of acute kidney injury in patients with acute pancreatitis admitted to the intensive care unit"
date: "2025-08-27"
description: "程毅松2022年125日发表于Chin Med J (Engl)"
categories: [machine learning]
type: article
---

## Course overview: MED3007 at UiO

Genomic data analysis is increasingly important both in medical research and in the clinical practice. In this course, you will learn the basic principles and concepts in the statistical analysis of genomic data. The course will focus on the three main tasks that are frequently involved in genomics: data visualisation, data screening and pre-processing, data modelling (prediction and classification). You will get a practical introduction to RStudio, the best statistical software for analysing genomic data, thus enabling you to perform basic programming tasks, to visualise and analyse genomic data, and to interpret the results.


## Course website in Quarto

We developed the course website in Quarto for lecture notes and R lab material. See website [here](https://ocbe-uio.github.io/course_med3007/).

The associated [Github repository](https://github.com/ocbe-uio/course_med3007) is also freely available.
